### ISSUE TITLE
Ajout des photos/vidéos par zip lors de la création d'un album

### ISSUE THREAD

**Issue by Powkachu** [Powkachu/ensiie-gallery#1]

**Comment by Powkachu** [comment]
On peut peut être utiliser zipper : http://packalyst.com/packages/package/chumper/zipper

**Comment by anthonycgi** [comment]
Simple ajout d'upload et extraction

TODO : 
- Verifier type des fichiers

**Comment by anthonycgi** [comment]
Vérification faite.
Les fichiers sont maintenant enregistrés dans le public directory

**Comment by anthonycgi** [comment]
http://stackoverflow.com/questions/30682421/how-to-protect-image-from-public-view-in-laravel-5/30682456#30682456

**Comment by anthonycgi** [comment]
Done!

Les vidéos sont ajoutées dans le folder videos lié à l'album.
Les images sont ajoutées dans le folder images lié à l'album.
Trois zips sont créés : Only images, only videos, et images + videoss
