### ISSUE TITLE
Créer le CSS pour l'affichage d'un album

### ISSUE THREAD

**Issue by Powkachu** [Powkachu/ensiie-gallery#12]
Avec deux sections : les photos et les vidéos.
Ne pas oublier les boutons d'action.

**Comment by Powkachu** [comment]
Fait pour les photos, encore les vidéos à ajouter

**Comment by anthonycgi** [comment]
Coté serveur, l'appel /videos/{id_album}/{id_media} est créé ! Plus qu'à l'appeler de la même façon que les photos (avec $media->getUrl() un truc comme ça)

**Comment by anthonycgi** [comment]
Ok pour diapo video
TODO : Générer les Thumbnail

**Comment by anthonycgi** [comment]
Impossible de gérer les thumbnails, il faut FFMPEG sur le systeme

**Comment by Powkachu** [comment]
Fait sans thumbnail !
