### ISSUE TITLE
Créer un meilleur design pour l'affichage des checkbox pour la suppression

### ISSUE THREAD

**Issue by anthonycgi** [Powkachu/ensiie-gallery#16]

**Comment by anthonycgi** [comment]
Au clic sur un bouton, les checkbox doivent s'afficher / se cacher et un nouveau bouton "Supprimer les éléments sélectionnés" doit s'afficher. Ce bouton ne doit être actif que lorsqu'au moins un élément est sélectionné !

**Comment by anthonycgi** [comment]
JS : Ok
CSS : Mid Ok (input basique, pas vraiment au milieu)

**Comment by Powkachu** [comment]
Au milieu maintenant !
